// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package helloworld

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PermissionDeniedDetail_PermissionDeniedType int32

const (
	PermissionDeniedDetail_TYPE_NONE PermissionDeniedDetail_PermissionDeniedType = 0
	PermissionDeniedDetail_TYPE_HOGE PermissionDeniedDetail_PermissionDeniedType = 1
)

var PermissionDeniedDetail_PermissionDeniedType_name = map[int32]string{
	0: "TYPE_NONE",
	1: "TYPE_HOGE",
}

var PermissionDeniedDetail_PermissionDeniedType_value = map[string]int32{
	"TYPE_NONE": 0,
	"TYPE_HOGE": 1,
}

func (x PermissionDeniedDetail_PermissionDeniedType) String() string {
	return proto.EnumName(PermissionDeniedDetail_PermissionDeniedType_name, int32(x))
}

func (PermissionDeniedDetail_PermissionDeniedType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{2, 0}
}

type PermissionDeniedDetail_PermissionDeniedCode int32

const (
	PermissionDeniedDetail_CODE_NONE    PermissionDeniedDetail_PermissionDeniedCode = 0
	PermissionDeniedDetail_CODE_UNKNOWN PermissionDeniedDetail_PermissionDeniedCode = 1
	PermissionDeniedDetail_CODE_FUGA    PermissionDeniedDetail_PermissionDeniedCode = 10000
)

var PermissionDeniedDetail_PermissionDeniedCode_name = map[int32]string{
	0:     "CODE_NONE",
	1:     "CODE_UNKNOWN",
	10000: "CODE_FUGA",
}

var PermissionDeniedDetail_PermissionDeniedCode_value = map[string]int32{
	"CODE_NONE":    0,
	"CODE_UNKNOWN": 1,
	"CODE_FUGA":    10000,
}

func (x PermissionDeniedDetail_PermissionDeniedCode) String() string {
	return proto.EnumName(PermissionDeniedDetail_PermissionDeniedCode_name, int32(x))
}

func (PermissionDeniedDetail_PermissionDeniedCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{2, 1}
}

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PermissionDeniedDetail struct {
	Type                 PermissionDeniedDetail_PermissionDeniedType `protobuf:"varint,1,opt,name=type,proto3,enum=PermissionDeniedDetail_PermissionDeniedType" json:"type,omitempty"`
	Code                 PermissionDeniedDetail_PermissionDeniedCode `protobuf:"varint,2,opt,name=code,proto3,enum=PermissionDeniedDetail_PermissionDeniedCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *PermissionDeniedDetail) Reset()         { *m = PermissionDeniedDetail{} }
func (m *PermissionDeniedDetail) String() string { return proto.CompactTextString(m) }
func (*PermissionDeniedDetail) ProtoMessage()    {}
func (*PermissionDeniedDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{2}
}

func (m *PermissionDeniedDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionDeniedDetail.Unmarshal(m, b)
}
func (m *PermissionDeniedDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionDeniedDetail.Marshal(b, m, deterministic)
}
func (m *PermissionDeniedDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionDeniedDetail.Merge(m, src)
}
func (m *PermissionDeniedDetail) XXX_Size() int {
	return xxx_messageInfo_PermissionDeniedDetail.Size(m)
}
func (m *PermissionDeniedDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionDeniedDetail.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionDeniedDetail proto.InternalMessageInfo

func (m *PermissionDeniedDetail) GetType() PermissionDeniedDetail_PermissionDeniedType {
	if m != nil {
		return m.Type
	}
	return PermissionDeniedDetail_TYPE_NONE
}

func (m *PermissionDeniedDetail) GetCode() PermissionDeniedDetail_PermissionDeniedCode {
	if m != nil {
		return m.Code
	}
	return PermissionDeniedDetail_CODE_NONE
}

func init() {
	proto.RegisterEnum("PermissionDeniedDetail_PermissionDeniedType", PermissionDeniedDetail_PermissionDeniedType_name, PermissionDeniedDetail_PermissionDeniedType_value)
	proto.RegisterEnum("PermissionDeniedDetail_PermissionDeniedCode", PermissionDeniedDetail_PermissionDeniedCode_name, PermissionDeniedDetail_PermissionDeniedCode_value)
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "HelloReply")
	proto.RegisterType((*PermissionDeniedDetail)(nil), "PermissionDeniedDetail")
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2) }

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x9b, 0x52, 0xac, 0x1d, 0x9b, 0xb2, 0x2c, 0x22, 0xc1, 0x93, 0xec, 0x41, 0x7a, 0xa8,
	0x39, 0x54, 0x1f, 0xc0, 0xd2, 0xc4, 0x04, 0x84, 0x4d, 0x89, 0x2d, 0xe2, 0x49, 0xa2, 0x19, 0x62,
	0x20, 0xc9, 0xc6, 0xec, 0x8a, 0xe4, 0x2d, 0x7a, 0xf7, 0x65, 0x25, 0x6b, 0x53, 0x85, 0x16, 0xc5,
	0xdb, 0xfe, 0xc3, 0xf7, 0xfd, 0x87, 0xd9, 0x01, 0xf2, 0x82, 0x59, 0x26, 0xde, 0x45, 0x95, 0xc5,
	0x76, 0x59, 0x09, 0x25, 0x18, 0x83, 0xa1, 0xdf, 0xcc, 0x42, 0x7c, 0x7d, 0x43, 0xa9, 0x28, 0x85,
	0x5e, 0x11, 0xe5, 0x68, 0x19, 0x67, 0xc6, 0x78, 0x10, 0xea, 0x37, 0x3b, 0x07, 0xd8, 0x30, 0x65,
	0x56, 0x53, 0x0b, 0xfa, 0x39, 0x4a, 0x19, 0x25, 0x2d, 0xd4, 0x46, 0xf6, 0xd1, 0x85, 0x93, 0x05,
	0x56, 0x79, 0x2a, 0x65, 0x2a, 0x0a, 0x07, 0x8b, 0x14, 0x63, 0x07, 0x55, 0x94, 0x66, 0xf4, 0x1a,
	0x7a, 0xaa, 0x2e, 0xbf, 0x8c, 0xd1, 0x74, 0x62, 0xef, 0xc7, 0x76, 0xc6, 0xcb, 0xba, 0xc4, 0x50,
	0x9b, 0x4d, 0xc3, 0xb3, 0x88, 0xd1, 0xea, 0xfe, 0xaf, 0x61, 0x2e, 0x62, 0x0c, 0xb5, 0xc9, 0xae,
	0xe0, 0x78, 0x5f, 0x3f, 0x35, 0x61, 0xb0, 0x7c, 0x58, 0xb8, 0x8f, 0x3c, 0xe0, 0x2e, 0xe9, 0x6c,
	0xa3, 0x1f, 0x78, 0x2e, 0x31, 0x98, 0xb7, 0x6b, 0x35, 0x9d, 0x0d, 0x36, 0x0f, 0x9c, 0xad, 0x45,
	0x60, 0xa8, 0xe3, 0x8a, 0xdf, 0xf2, 0xe0, 0x9e, 0x13, 0x83, 0x8e, 0x36, 0xc0, 0xcd, 0xca, 0x9b,
	0x91, 0x35, 0x9f, 0xae, 0x0d, 0xe8, 0x7b, 0x15, 0xa2, 0xc2, 0x8a, 0x8e, 0xe1, 0xf0, 0x2e, 0xaa,
	0xf5, 0x52, 0xa9, 0x69, 0xff, 0xfc, 0x80, 0xd3, 0x23, 0xfb, 0x7b, 0xd7, 0xac, 0x43, 0x2f, 0xc0,
	0x6c, 0xc9, 0x59, 0x12, 0xa5, 0xc5, 0x1f, 0xf8, 0x04, 0x86, 0x2d, 0xee, 0x8b, 0x04, 0x7f, 0xa7,
	0x9f, 0x0e, 0xf4, 0x0d, 0x5c, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xb3, 0x78, 0xd7, 0x17,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// Sends another greeting
	SayHelloAgain(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// Hoge
	SayHelloHoge(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayHelloAgain(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/Greeter/SayHelloAgain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayHelloHoge(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/Greeter/SayHelloHoge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	// Sends another greeting
	SayHelloAgain(context.Context, *HelloRequest) (*HelloReply, error)
	// Hoge
	SayHelloHoge(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayHelloAgain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHelloAgain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Greeter/SayHelloAgain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHelloAgain(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayHelloHoge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHelloHoge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Greeter/SayHelloHoge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHelloHoge(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "SayHelloAgain",
			Handler:    _Greeter_SayHelloAgain_Handler,
		},
		{
			MethodName: "SayHelloHoge",
			Handler:    _Greeter_SayHelloHoge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}
